### ISSUE TITLE
Crafting masterpieces doesn't rank up the player

### ISSUE THREAD

**Issue by lcdr** [MellonNet/mln-backend-emulator#1]
Right now ranking up by crafting masterpieces is not implemented.

To fix:

- Change [use_blueprint](https://github.com/MellonNet/mln-backend-emulator/blob/master/mln/services/misc.py#L33) to check if the item to be created is a masterpiece (`if blueprint_info.build.type == ItemType.MASTERPIECE`)
    - If yes, check if the user already has the item (`user.inventory.filter(item_id=blueprint_info.build_id).exists()`)
        - If the user already has the masterpiece, return
    - If the user doesn't have the masterpiece, increase the user's rank by one 
        `user.profile.rank += 1`
        `user.profile.save()` 
- Add [service tests](https://github.com/MellonNet/mln-backend-emulator/blob/master/mln/tests/services/test_misc.py) to test the new behavior:
    - Create a database cls_setup function that defines a masterpiece (use [`module`](https://github.com/MellonNet/mln-backend-emulator/blob/master/mln/tests/services/test_misc.py#L11) as guidance)
    - Create a database setup function that adds the masterpiece to the user's inventory (use [`has_module`](https://github.com/MellonNet/mln-backend-emulator/blob/master/mln/tests/services/test_misc.py#L20) as guidance)
    - Add a test for crafting a masterpiece, check that the rank is increased and the masterpiece is created.
    - Add a test for crafting a duplicate masterpiece, check that the rank is not increased and no extra masterpiece is created.
- Run the tests locally and verify that they pass (`python manage.py test`  (you can add `--failfast --keepdb` to make it a bit faster on later runs)
- Edit README.md to move "Masterpieces" from "Not yet implemented" to "Implemented"

**Comment by wertercatt** [comment]
Hi, I'm trying to create the tests, but I'm having trouble getting it to trigger my rankup code. Can you help me see what I'm doing wrong? https://github.com/wertercatt/mln-backend-emulator

**Comment by wertercatt** [comment]
This issue is fixed with pull request #8, so it should probably be closed.
